### ISSUE TITLE
QR code not printing

### ISSUE THREAD

**Issue by zmaglica** [humbertopiaia/escpos-commands-js#1]
Hello,

thank you for your time and effort in creating this package. I used your package in my project and I stumble upon printing QRCode. I used _qrcode_ function and it only prints value of string I pass to it.

Do you know why it is not working?

Also, here is code I use:

`import React, {Component} from 'react';
import {connect} from 'react-redux';
import Escpos from 'escpos-commands/src/escpos';

class Test extends Component {

    print = () => {
        let result = new Escpos()
            .init()
            .align('ct')
            .boldOn()
            .text("Testing")
            .boldOff()
            .feed(1)
            .qrcode("test")
            .feed(1)
            .cut()
        ;

        chrome.runtime.sendMessage("chklklmchflbhdhlheeddigflianadik", result);
    }

    render() {

        return (
            <div className="wrapper wrapper-content animated fadeInRight">
                <div className="row">
                    <button onClick={this.print}> Print me</button>
                </div>
            </div>
        )
    }
`}`

```
function mapStateToProps(state) {
    return {
        posItems: state.auth.config.posItems,
    };
}

export default connect(mapStateToProps, {})(Test);`
```

**Comment by NicksonYap** [comment]
Thanks to your code, I actually got it working!

**Comment by alejandrojcc** [comment]
Hi @NicksonYap How did you put into operation the qr? please help me I need finish with this code,
@zmaglica can you print qr?

Thanks you.

**Comment by zmaglica** [comment]
> Hi @NicksonYap How did you put into operation the qr? please help me I need finish with this code,
> @zmaglica can you print qr?
> 
> Thanks you.

I manage to print it as an image. I checked the documentation of POS printer and extended package with my own code for printing image. Also you can check https://github.com/song940/node-escpos where you can print image.
